# Generated by Django 3.0.7 on 2020-06-25 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=256)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('visible', models.CharField(choices=[('V', 'Visible'), ('U', 'User')], default='U', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(max_length=256)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('visible', models.CharField(choices=[('V', 'Visible'), ('U', 'User')], default='U', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('library', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('ImageUserRelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.ImageUserRelation')),
            ],
        ),
    ]
